import { Theme, Material } from './types';

export const THEME_PRESETS: Theme[] = [
  {
    name: 'Hijau Toska Gelap',
    bgMain: '#05332e',
    bgSidebar: '#03211e',
    accent: '#14b8a6',
    textMain: '#e8f5e0',
    textSidebar: '#e8f5e0',
    isDark: true,
  },
  {
    name: 'Magenta',
    bgMain: '#a8007b',
    bgSidebar: '#7a0050',
    accent: '#ff8fdf',
    textMain: '#e8f5e0',
    textSidebar: '#e8f5e0',
    isDark: true,
  },
  {
    name: 'Biru Navy',
    bgMain: '#003385',
    bgSidebar: '#002663',
    accent: '#3b82f6',
    textMain: '#e8f5e0',
    textSidebar: '#e8f5e0',
    isDark: true,
  },
  {
    name: 'Hutan',
    bgMain: '#033003',
    bgSidebar: '#022102',
    accent: '#4ade80',
    textMain: '#ffffff',
    textSidebar: '#ffffff',
    isDark: true,
  },
  {
    name: 'Grape',
    bgMain: '#410052',
    bgSidebar: '#2d0039',
    accent: '#d8b4fe',
    textMain: '#ffffff',
    textSidebar: '#ffffff',
    isDark: true,
  },
  {
    name: 'Indigo',
    bgMain: '#1e1b4b',
    bgSidebar: '#151233',
    accent: '#818cf8',
    textMain: '#f5f3ff',
    textSidebar: '#f5f3ff',
    isDark: true,
  },
  {
    name: 'Rose',
    bgMain: '#4c0519',
    bgSidebar: '#360312',
    accent: '#fb7185',
    textMain: '#fff1f2',
    textSidebar: '#fff1f2',
    isDark: true,
  },
  {
    name: 'Hitam',
    bgMain: '#000000',
    bgSidebar: '#000000',
    accent: '#ffffff',
    textMain: '#ffffff',
    textSidebar: '#ffffff',
    isDark: true,
  },
];

export const ALL_MATERIALS: Material[] = [];
